stages:
  prepare:
    cmd: python src/preprocess_ml1m.py
    deps:
    - ml1m/ml-1m.txt
    - src/preprocess_ml1m.py
    outs:
    - ml1m/dataset_stats.json
    - ml1m/item_cnt.pkl
    - ml1m/test
    - ml1m/train
    - ml1m/val
