[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "logq"
version = "0.1.0"
description = "LogQ project"
readme = "README.md"
requires-python = ">=3.9"

[tool.setuptools]
packages = ["logq"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
# list of all codes - https://docs.astral.sh/ruff/rules/
select = ["E4", "E7", "E9", "F", "W", "I"]
ignore = ["F403", "E721"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.ruff.format]
quote-style = "preserve"